"""Training-data preparation for the creator's persona model.

Realistic AI video of a real person requires training a persona/LoRA
model on HER content with a GPU. CreatorForge does not ship a model and
cannot train one for you here -- these helpers turn her catalog into the
dataset + configs that real training tools (kohya_sd, diffusers) expect.

Pipeline:
    1. :func:`build_dataset_manifest` -- pick catalog images, write a
       manifest CSV (path, caption placeholder, split).
    2. :func:`write_caption_files` -- write one ``.txt`` caption per image
       (kohya-style ``<trigger>`` token captions).
    3. :func:`write_kohya_config` -- generate a kohya_sd LoRA training
       TOML with sane defaults; you run it with scripts/train_lora.sh.

See docs/VIDEO.md for realistic GPU/time expectations.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any


def build_dataset_manifest(
    items: list[dict[str, Any]],
    out_csv: str | Path,
    *,
    trigger_word: str = "creatorpersona",
    train_split: float = 0.9,
) -> Path:
    """Write a manifest CSV: ``path,caption,split,width,height``.

    Items should be image rows from the catalog. Captions are placeholders
    -- edit them to describe each shot before training.
    """
    out = Path(out_csv)
    out.parent.mkdir(parents=True, exist_ok=True)
    n = len(items)
    split_at = max(1, int(n * train_split))
    with out.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["path", "caption", "split", "width", "height"])
        for i, item in enumerate(items):
            split = "train" if i < split_at else "val"
            caption = f"{trigger_word} woman, photo"
            w.writerow([item["path"], caption, split,
                        item.get("width") or "", item.get("height") or ""])
    return out


def write_caption_files(
    manifest_csv: str | Path,
    out_dir: str | Path,
    *,
    trigger_word: str = "creatorpersona",
    template: str = "{trigger} woman, {note}",
) -> int:
    """Write one ``<stem>.txt`` caption per image in the dataset dir.

    Copies (or expects) images alongside; returns number of captions written.
    ``note`` defaults to the manifest caption so you can hand-edit files.
    """
    import shutil

    manifest_csv = Path(manifest_csv)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    with manifest_csv.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            src = Path(row["path"])
            if not src.is_file():
                continue
            dst = out_dir / src.name
            if not dst.exists():
                shutil.copy2(src, dst)
            caption = template.format(trigger=trigger_word,
                                      note=row.get("caption", ""))
            (out_dir / (dst.stem + ".txt")).write_text(caption + "\n",
                                                       encoding="utf-8")
            count += 1
    return count


def write_kohya_config(
    out_toml: str | Path,
    *,
    train_data_dir: str,
    output_dir: str,
    output_name: str = "creator-persona-lora",
    pretrained_model: str = "",
    resolution: int = 1024,
    train_batch_size: int = 1,
    max_train_steps: int = 1500,
    learning_rate: float = 1e-4,
    network_dim: int = 16,
    network_alpha: int = 8,
    mixed_precision: str = "bf16",
    save_every_n_steps: int = 250,
) -> Path:
    """Generate a kohya_sd LoRA training TOML.

    You must set ``pretrained_model`` to a base checkpoint you have the
    right to fine-tune, and run training on a GPU machine (see
    scripts/train_lora.sh and docs/VIDEO.md).
    """
    out = Path(out_toml)
    out.parent.mkdir(parents=True, exist_ok=True)
    toml = f"""# Generated by creator-forge. Run with: bash scripts/train_lora.sh {out}
# Requires: kohya_sd (sd-scripts), a CUDA GPU, and your dataset.
[model]
pretrained_model_name_or_path = "{pretrained_model}"

[dataset]
train_data_dir = "{train_data_dir}"
resolution = {resolution}
caption_extension = ".txt"

[training]
output_dir = "{output_dir}"
output_name = "{output_name}"
train_batch_size = {train_batch_size}
max_train_steps = {max_train_steps}
learning_rate = {learning_rate}
lr_scheduler = "cosine"
optimizer_type = "AdamW8bit"
mixed_precision = "{mixed_precision}"
save_every_n_steps = {save_every_n_steps}
save_model_as = "safetensors"
cache_latents = true
cache_text_encoder_outputs = true

[network]
network_module = "networks.lora"
network_dim = {network_dim}
network_alpha = {network_alpha}
"""
    out.write_text(toml, encoding="utf-8")
    return out
